name = "lpa_vesicle_model"
uuid = "047936c9-78ec-4b0f-b7e8-4856125ff52c"
authors = ["Konstantin Stadler <konstantin.stadler@ntnu.no>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
